### ISSUE TITLE
Action '-D NO_DETACH -C Include 'path/to/clone/php-getting-started/vendor/heroku/heroku-buildpack-php/conf/apache2/heroku.conf' failed on Ubuntu 14.04

### ISSUE THREAD

**Issue by johansyd** [heroku/php-getting-started#12]
Having issues with running the getting-started app locally. I symlinked apachectl to httpd to get to the point that I could start httpd, but didn't get any further after that.

```
 $ /usr/sbin/apachectl -v
 Server version: Apache/2.4.16 (Ubuntu) 
 Server built:   2015-09-08T00:00:00

 $ php-fpm -v
 PHP 5.5.30-1+deb.sury.org~trusty+1 (fpm-fcgi) (built: Oct  4 2015 16:27:23)
```

When running the following command:

```
vendor/bin/heroku-php-apache2 web/
```

I get:

DOCUMENT_ROOT changed to 'web/'
4 processes at 128MB memory limit.
Starting php-fpm...
Starting httpd...
Application ready for connections on port 19661.
Usage: /usr/sbin/apache2 [-D name] [-d directory] [-f file]
                         [-C "directive"] [-c "directive"]
                         [-k start|restart|graceful|graceful-stop|stop]
                         [-v] [-V] [-h] [-l] [-L] [-t] [-T] [-S] [-X]
Options:
  -D name            : define a name for use in <IfDefine name> directives
  -d directory       : specify an alternate initial ServerRoot
  -f file            : specify an alternate ServerConfigFile
  -C "directive"     : process directive before reading config files
  -c "directive"     : process directive after reading config files
  -e level           : show startup errors of level (see LogLevel)
  -E file            : log startup errors to file
  -v                 : show version number
  -V                 : show compile settings
  -h                 : list available command line options (this page)
  -l                 : list compiled in modules
  -L                 : list available configuration directives
  -t -D DUMP_VHOSTS  : show parsed vhost settings
  -t -D DUMP_RUN_CFG : show parsed run settings
  -S                 : a synonym for -t -D DUMP_VHOSTS -D DUMP_RUN_CFG
  -t -D DUMP_MODULES : show all loaded modules 
  -M                 : a synonym for -t -D DUMP_MODULES
  -t                 : run syntax check for config files
  -T                 : start without DocumentRoot(s) check
  -X                 : debug mode (only one worker, do not detach)
Action '-D NO_DETACH -c Include /home/johan/src/heroku/php-getting-started/vendor/heroku/heroku-buildpack-php/conf/apache2/heroku.conf' failed.
The Apache error log may have more information.
Process exited unexpectedly: httpd
Going down, terminating child processes...

**Comment by jonmountjoy** [comment]
Please open a support ticket on Heroku - this seems unrelated to this app in particular.
