### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by kravenoff42** [heroku/php-getting-started#18]
Guided tour page. First paragraph.

https://devcenter.heroku.com/articles/getting-started-with-php?c=70130000000NhRJAA0&utm_campaign=Onboarding-Nurture-Email-1&utm_medium=email&utm_source=nurture&utm_content=devcenter&utm_term=start-php#set-up

says: "Heroku Command Line Interface (CLI), formerly known at the Heroku Toolbelt. "
should say: "Heroku Command Line Interface (CLI), formerly known **as** the Heroku Toolbelt.

**Comment by jonmountjoy** [comment]
Thanks, fixed!
