### ISSUE TITLE
Silex is being deprecated away as of June 2018

### ISSUE THREAD

**Issue by deborah-ufw** [heroku/php-getting-started#27]
From Silex home page:

Silex is in maintenance mode. Ends of life is set to June 2018. 
Use Symfony 4 instead. Read more on Symfony's blog.

**Comment by Pepper-Wood** [comment]
For others who are seeing this, here is an official Heroku blog that details how to set up a Symfony 4/5 web application: https://devcenter.heroku.com/articles/deploying-symfony4
