### ISSUE TITLE
Composer self-update

### ISSUE THREAD

**Issue by wiesson** [heroku/php-getting-started#5]
First, the php-getting-started example is totally fine and works good to me, this is just a "notice".
During the tutorial, the Heroku console is telling me that I should update the composer itself. I've read the docs, but I still don't geht how to run ```composer self-update``` on heroku?

```shell
(...)
remote: -----> Installing dependencies...
remote:        Composer version 1.0-dev (c5cd184767001f34177da99e91f7a6dcf8ad27f6) 2015-03-24 01:36:30
remote:        Warning: This development build of composer is over 30 days old. It is recommended to update it by running "/app/.heroku/php/bin/composer self-update" to get the latest version.
remote:        Loading composer repositories with package information
(...)
```

**Comment by jonmountjoy** [comment]
Thanks @wiesson, this is an innocuous warning, and you can safely ignore it.

**Comment by wiesson** [comment]
Ok, but am I able to update the composer?

**Comment by jonmountjoy** [comment]
It's included as part of the [buildpack](https://github.com/heroku/heroku-buildpack-php) - I guess you could fork that and do it yourself - but I would recommend sticking with the default, maintained buildpack.  It will, for example, receive a composer update when needed.

**Comment by wiesson** [comment]
Ok, then I will leave it as it is. Thanks!
